services:
  - type: web
    name: baplikasyon
    env: node
    buildCommand: chmod +x install.sh && ./install.sh
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        value: mongodb+srv://barisboga:951753@cluster0.9ove7.mongodb.net/baplikasyon 